name: generate animation SNK

on:
  schedule:
    - cron: "0 */6 * * *" # 每6小时运行一次
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libjpeg-dev \
            libpango1.0-dev \
            libgif-dev \
            librsvg2-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate github-snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: ML-Leslie
          outputs: |
            dist/github-snake.svg?color_snake=#ff69b4
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff69b4
            dist/ocean.gif?color_snake=#ff69b4

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
